# Generated by Django 4.2.30 on 2026-05-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hscore',
            new_name='h_score_hospita_9755aa_idx',
            old_name='h_score_hospita_1f3626_idx',
        ),
    ]
